"""player account

Revision ID: 39e5651db3ac
Revises: eba0bcef8192
Create Date: 2026-09-10 02:15:42.674488
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "39e5651db3ac"
down_revision = "eba0bcef8192"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "player_account",
        sa.Column("name_key", sa.Text(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("name_key"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("player_account")
    # ### end Alembic commands ###
