"""initial schema

Revision ID: 8d8249785eec
Revises:
Create Date: 2026-08-29 15:43:40.246843
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "8d8249785eec"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "series",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("title_en", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "tag",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "game_mode",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("blurb", sa.Text(), nullable=True),
        sa.Column("series_id", sa.Integer(), nullable=True),
        sa.Column("required_tags", sa.ARRAY(sa.Integer()), nullable=False),
        sa.Column("difficulty_min", sa.SmallInteger(), nullable=False),
        sa.Column("difficulty_max", sa.SmallInteger(), nullable=False),
        sa.Column("question_count", sa.SmallInteger(), nullable=False),
        sa.Column("seconds_per_q", sa.SmallInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["series_id"],
            ["series.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "question",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("series_id", sa.Integer(), nullable=True),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("media_ref", sa.Text(), nullable=True),
        sa.Column("difficulty", sa.SmallInteger(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.CheckConstraint("difficulty between 1 and 3", name="difficulty_range"),
        sa.ForeignKeyConstraint(
            ["series_id"],
            ["series.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "answer_option",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("question_id", sa.BigInteger(), nullable=False),
        sa.Column("ordinal", sa.SmallInteger(), nullable=False),
        sa.Column("label", sa.Text(), nullable=False),
        sa.Column("is_correct", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["question_id"], ["question.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "one_correct_per_question",
        "answer_option",
        ["question_id"],
        unique=True,
        postgresql_where=sa.text("is_correct"),
    )
    op.create_index("uq_option_ordinal", "answer_option", ["question_id", "ordinal"], unique=True)
    op.create_table(
        "game",
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("room_code", sa.Text(), nullable=False),
        sa.Column("mode_id", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("question_count", sa.SmallInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["mode_id"],
            ["game_mode.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "question_tag",
        sa.Column("question_id", sa.BigInteger(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["question_id"], ["question.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tag_id"], ["tag.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("question_id", "tag_id"),
    )
    op.create_table(
        "game_answer",
        sa.Column("game_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("round_index", sa.SmallInteger(), nullable=False),
        sa.Column("player_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("question_id", sa.BigInteger(), nullable=False),
        sa.Column("option_id", sa.BigInteger(), nullable=True),
        sa.Column("elapsed_ms", sa.Integer(), nullable=True),
        sa.Column("is_correct", sa.Boolean(), nullable=False),
        sa.Column("points", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["game_id"], ["game.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["option_id"],
            ["answer_option.id"],
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["question.id"],
        ),
        sa.PrimaryKeyConstraint("game_id", "round_index", "player_id"),
    )
    op.create_table(
        "game_player",
        sa.Column("game_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("player_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("final_score", sa.Integer(), nullable=False),
        sa.Column("final_rank", sa.SmallInteger(), nullable=False),
        sa.Column("total_elapsed_ms", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["game_id"], ["game.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("game_id", "player_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("game_player")
    op.drop_table("game_answer")
    op.drop_table("question_tag")
    op.drop_table("game")
    op.drop_index("uq_option_ordinal", table_name="answer_option")
    op.drop_index(
        "one_correct_per_question",
        table_name="answer_option",
        postgresql_where=sa.text("is_correct"),
    )
    op.drop_table("answer_option")
    op.drop_table("question")
    op.drop_table("game_mode")
    op.drop_table("tag")
    op.drop_table("series")
    # ### end Alembic commands ###
