"""player wallet

Revision ID: eba0bcef8192
Revises: 8d8249785eec
Create Date: 2026-09-08 23:42:37.446058
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "eba0bcef8192"
down_revision = "8d8249785eec"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "player_wallet",
        sa.Column("name_key", sa.Text(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=False),
        sa.Column("coins", sa.BigInteger(), nullable=False),
        sa.Column("games_played", sa.Integer(), nullable=False),
        sa.Column("wins", sa.Integer(), nullable=False),
        sa.Column("best_score", sa.Integer(), nullable=False),
        sa.Column("lifetime_score", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("name_key"),
    )
    op.create_index(
        "ix_wallet_coins", "player_wallet", [sa.literal_column("coins DESC")], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_wallet_coins", table_name="player_wallet")
    op.drop_table("player_wallet")
    # ### end Alembic commands ###
